import {PublicClientApplication,InteractionRequiredAuthError} from "@azure/msal-browser";
import {buildTaskWorkbook,parseTaskWorkbook,WORKBOOK_MIME as TASK_MIME} from "./task-workbook.js";
import {buildTodayWorkbook,parseTodayWorkbook,WORKBOOK_MIME as TODAY_MIME} from "./today-workbook.js";
import "./app-config.js";
import "./styles.css";
import "./sync-status.css";

const CONFIG=window.BUCHO_TODAY_CONFIG;
const STORAGE_KEY="bucho-today-records-v1",BASE_KEY="bucho-today-base-v1",PATCH_KEY="bucho-today-task-patches-v1",DEVICE_KEY="bucho-today-device-v1",LOGIN_KEY="bucho-today-login-v1",SETTINGS_KEY="bucho-today-settings-v1";
const SYSTEM_PREFIX="ZZZ-TC-",DEPENDENCY_PREFIX=`${SYSTEM_PREFIX}DEPENDENCY-`,CALENDAR_PREFIX=`${SYSTEM_PREFIX}CALENDAR-`;
const DEFAULT_SETTINGS={owner:"福本",dayStart:"08:00",dayEnd:"20:00",lunchStart:"12:00",lunchEnd:"13:00",buffer:30};
const SECTIONS=["守る","進める","育てる"],TEMPS=["🔥HOT","🟠WARM","🧊COLD"],STATUSES=["未着手","進行中","確認待ち","保留","完了"];
const PROMPTS=[
  ["judgement","誰の判断待ちを解消するか","止まっている仕事のボトルネックを特定"],
  ["stop","今日止めるものは何か","やらない決断で、リソースを守る"],
  ["report","上司へ何を上げるか","進捗・課題・判断が必要な事項を整理"],
  ["tomorrow","明日の詰まりを何で除くか","先回りして、滞りを防ぐ"]
];

const readObject=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return structuredClone(fallback);}};
const state={
  date:tokyoDate(),records:readObject(STORAGE_KEY),base:readObject(BASE_KEY),taskPatches:readObject(PATCH_KEY),tasks:{},events:[],account:null,msal:null,busy:false,syncTimer:null,
  settings:{...DEFAULT_SETTINGS,...readObject(SETTINGS_KEY)},taskRemote:null,todayRemote:null,lastError:null,editingPlan:""
};
const $=id=>document.getElementById(id),esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const nowIso=()=>new Date().toISOString();
function tokyoDate(){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date());}
function tokyoTime(){return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit"}).format(new Date());}
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=`today-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;localStorage.setItem(DEVICE_KEY,id);}return id;}
function store(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.records));localStorage.setItem(BASE_KEY,JSON.stringify(state.base));localStorage.setItem(PATCH_KEY,JSON.stringify(state.taskPatches));localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings));}
function activeTodayRecords(date=state.date){return Object.values(state.records).filter(r=>!r.deleted&&r.date===date);}
function activeTasks(){return Object.values(state.tasks).filter(t=>!t.deleted&&!String(t.id||"").startsWith(SYSTEM_PREFIX));}
function plans(){return activeTodayRecords().filter(r=>r.kind==="TASK_PLAN").sort((a,b)=>timeToMin(a.start)-timeToMin(b.start)||a.sortOrder-b.sortOrder);}
function dayRecord(){return activeTodayRecords().find(r=>r.kind==="DAY")||null;}
function newRecord(kind,extra={}){const stamp=Date.now().toString(36),record={id:`${kind}-${state.date}-${stamp}-${Math.random().toString(36).slice(2,5)}`,date:state.date,kind,sourceId:"",title:"",subtitle:"",start:"",end:"",plannedHours:0,section:"進める",todayDone:false,focusRank:0,sortOrder:Date.now(),notes:"",value:"",updatedAt:nowIso(),updatedBy:deviceId(),revision:1,deleted:false,...extra};state.records[record.id]=record;return record;}
function touchRecord(record,changes){Object.assign(record,changes,{updatedAt:nowIso(),updatedBy:deviceId(),revision:(Number(record.revision)||0)+1});store();scheduleSync();}
function ensureDayRecord(){let record=dayRecord();if(!record)record=newRecord("DAY",{sourceId:"DAY",title:"一日の状態",value:JSON.stringify({confirmed:false,closed:false})});return record;}
function dayState(){try{return JSON.parse(dayRecord()?.value||"{}");}catch{return{};}}
function saveDayState(changes){const record=ensureDayRecord();touchRecord(record,{value:JSON.stringify({...dayState(),...changes})});}
function addDays(date,days){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function timeToMin(value){const [h=0,m=0]=String(value||"0:0").split(":").map(Number);return h*60+m;}
function minToTime(value){const n=Math.max(0,Math.min(1439,Math.round(value)));return`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;}
function duration(start,end){return Math.max(0,timeToMin(end)-timeToMin(start));}
function formatHours(hours){const n=Math.round((Number(hours)||0)*4)/4;return`${Number(n.toFixed(2))}h`;}
function formatLongMinutes(mins){const h=Math.floor(mins/60),m=Math.round(mins%60);return`${h?`${h}時間`:""}${m?`${m}分`:h?"":"0分"}`;}
function dateLabel(){const d=new Date(`${state.date}T00:00:00+09:00`);return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(d);}
function tempValue(v){const map={"★★★":"🔥HOT","★★":"🟠WARM","★":"🧊COLD"};return map[v]||TEMPS.includes(v)&&v||"🟠WARM";}
function taskSection(task){if(task.category==="防衛"||task.category==="ルーティン")return"守る";if(task.category==="能力")return"育てる";return"進める";}
function dependencyIds(taskId){const record=state.tasks[`${DEPENDENCY_PREFIX}${taskId}`];if(!record||record.deleted||!record.nextAction)return[];try{return JSON.parse(record.nextAction);}catch{return String(record.nextAction).split(",").filter(Boolean);}}
function dependenciesReady(task){return dependencyIds(task.id).every(id=>state.tasks[id]?.status==="完了");}
function taskHasFixedCalendar(task){const record=state.tasks[`${CALENDAR_PREFIX}${task.id}`];return Boolean(record&&!record.deleted&&String(record.nextAction||"").slice(0,10)===state.date&&record.blocker);}
function taskScore(task){const due=task.dueDate||"9999-12-31",next=task.nextTouchDate||"9999-12-31";let score=0;if(task.todayPlacement==="必ず入れる")score+=100000;if(due<state.date)score+=50000;if(next<=state.date)score+=20000;if(due===state.date)score+=15000;score+=tempValue(task.priority).includes("HOT")?8000:tempValue(task.priority).includes("WARM")?3000:0;if(due!=="9999-12-31")score+=Math.max(0,3000-Math.max(0,(new Date(due)-new Date(state.date))/86400000)*100);return score;}
function eligibleTasks(){return activeTasks().filter(t=>String(t.owner||"").trim()===state.settings.owner&&t.status!=="完了"&&t.status!=="保留"&&t.todayPlacement!=="入れない"&&dependenciesReady(t)&&!taskHasFixedCalendar(t)).sort((a,b)=>taskScore(b)-taskScore(a)||String(a.dueDate||"").localeCompare(String(b.dueDate||"")));}

document.querySelector("#app").innerHTML=`
<main class="app-shell">
 <header class="topbar">
  <div class="brand"><span class="brand-icon">🏢</span><div><h1>部門責任者 TODAY <em>V1.1</em></h1><p>現場を動かし、未来をつくる｜今日という一日を、確かな前進に</p></div></div>
  <div class="date-nav"><button id="prevDay" aria-label="前日">‹</button><div><strong id="dateLabel"></strong><small>やるべきことを見える化し、現場が回る一日をつくる</small></div><button id="calendarBtn" aria-label="今日">▣</button><button id="nextDay" aria-label="翌日">›</button></div>
  <div class="header-actions"><button id="rebuildBtn">↻ 再構成</button><button id="confirmBtn" class="primary">✓ 今日を確定</button><span id="syncState" class="sync-indicator local" role="status" aria-live="polite">端末内保存</span><button id="syncBtn">↻ 同期</button><button id="loginBtn">Microsoftログイン</button><button id="settingsBtn" aria-label="設定">⚙</button></div>
 </header>
 <section class="metrics" id="metrics"></section>
 <section class="dashboard">
  <section class="timeline-panel panel"><div class="panel-head"><div><h2>▣ 今日の時間軸</h2><p>Outlookの予定とTASK CONTROLのタスクを統合</p></div><button id="allTasksBtn">☷ すべて表示</button></div><div id="timeline" class="timeline"></div></section>
  <section class="right-stack">
   <section id="sectionCards" class="section-cards"></section>
   <section class="manager-panel panel"><div class="panel-head"><div><h2>◉ 部門責任者として今日見ること</h2></div><p>現場・人・仕事の流れを俯瞰し、打ち手を決める</p></div><div id="promptGrid" class="prompt-grid"></div></section>
   <section class="focus-panel panel"><div class="panel-head"><div><h2>◎ 今日の重点3本</h2></div><p>今日、必ず前に進める3つに集中する</p></div><div id="focusList"></div></section>
  </section>
 </section>
 <footer class="today-footer"><label>✎ 割込みメモ<input id="interruptMemo" placeholder="気づいたことを、すぐにメモ…"></label><button id="carryBtn">▤ 持越し候補 <b id="carryCount">0</b><small>今日やり切れないものを整理</small></button><button id="closeDayBtn">☾ 今日を閉じる<small>1日の振り返りを行います</small></button></footer>
 <div class="connection-line"><span id="accountInfo">Microsoft未接続</span><button id="todayExcelBtn" disabled>TODAY Master</button><button id="taskExcelBtn" disabled>TASK CONTROL Master</button><button id="diagnosticBtn">診断情報</button></div>
</main>
<dialog id="planDialog"><form id="planForm"><div class="dialog-head"><div><small>TODAY PLAN</small><h2 id="planTitle">今日のタスク</h2></div><button type="button" data-close>×</button></div><p id="planSubtitle" class="dialog-subtitle"></p><div class="form-grid"><label>開始<input name="start" type="time" step="900" required></label><label>終了<input name="end" type="time" step="900" required></label><label>領域<select name="section">${SECTIONS.map(x=>`<option>${x}</option>`).join("")}</select></label><label>重点順位<select name="focusRank"><option value="0">重点外</option><option value="1">01</option><option value="2">02</option><option value="3">03</option></select></label><label>今日分<select name="todayDone"><option value="false">未完了</option><option value="true">今日分完了</option></select></label><label>タスク状態<select name="status">${STATUSES.map(x=>`<option>${x}</option>`).join("")}</select></label><label>進捗<input name="progress" type="number" min="0" max="100" step="5"></label><label>温度感<select name="priority">${TEMPS.map(x=>`<option>${x}</option>`).join("")}</select></label><label>期日<input name="dueDate" type="date"></label><label>次に触る日<input name="nextTouchDate" type="date"></label><label>想定所要時間（h）<input name="expectedHours" type="number" min="0" max="10000" step="0.25"></label><label class="span-2">今日のメモ<textarea name="notes" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" id="removePlanBtn" class="danger">今日から外す</button><span></span><button type="button" data-close>キャンセル</button><button type="submit" class="primary">保存して閉じる</button></div></form></dialog>
<dialog id="candidateDialog"><div class="dialog-head"><div><small>TASK CANDIDATES</small><h2>今日へ追加</h2></div><button type="button" data-close>×</button></div><div id="candidateList" class="candidate-list"></div></dialog>
<dialog id="carryDialog"><div class="dialog-head"><div><small>CARRY OVER</small><h2>持越し候補</h2></div><button type="button" data-close>×</button></div><div id="carryList" class="candidate-list"></div></dialog>
<dialog id="settingsDialog"><form id="settingsForm"><div class="dialog-head"><div><small>SETTINGS</small><h2>今日の自動作成ルール</h2></div><button type="button" data-close>×</button></div><div class="form-grid"><label>担当者<input name="owner" required></label><label>余白率（％）<input name="buffer" type="number" min="0" max="70" step="5"></label><label>表示開始<input name="dayStart" type="time" step="900"></label><label>表示終了<input name="dayEnd" type="time" step="900"></label><label>休憩開始<input name="lunchStart" type="time" step="900"></label><label>休憩終了<input name="lunchEnd" type="time" step="900"></label></div><p class="hint">Outlook予定を先に固定し、残り時間のうち余白率を除いた範囲へタスクを配置します。</p><div class="dialog-actions"><span></span><button type="button" data-close>キャンセル</button><button type="submit" class="primary">保存</button></div></form></dialog>
<dialog id="diagnosticDialog"><div class="dialog-head"><h2>診断情報</h2><button type="button" data-close>×</button></div><pre id="diagnosticText"></pre></dialog>`;

function render(){
  $("dateLabel").textContent=dateLabel();
  const ds=dayState();
  $("confirmBtn").classList.toggle("confirmed",Boolean(ds.confirmed));
  $("confirmBtn").textContent=ds.confirmed?"✓ 確定済み":"✓ 今日を確定";
  $("closeDayBtn").classList.toggle("closed",Boolean(ds.closed));
  renderMetrics();renderTimeline();renderSections();renderPrompts();renderFocus();renderFooter();updateAccount();
}
function occupiedIntervals(includePlans=true){const list=[];state.events.filter(e=>!e.isAllDay).forEach(e=>list.push({start:timeToMin(eventTime(e.start)),end:timeToMin(eventTime(e.end)),type:"event",item:e}));if(state.settings.lunchStart&&state.settings.lunchEnd)list.push({start:timeToMin(state.settings.lunchStart),end:timeToMin(state.settings.lunchEnd),type:"lunch"});if(includePlans)plans().forEach(p=>list.push({start:timeToMin(p.start),end:timeToMin(p.end),type:"plan",item:p}));return list.filter(x=>x.end>x.start).sort((a,b)=>a.start-b.start);}
function freeSlots(includePlans=true){const start=timeToMin(state.settings.dayStart),end=timeToMin(state.settings.dayEnd),busy=occupiedIntervals(includePlans),slots=[];let cursor=start;for(const interval of busy){if(interval.end<=start||interval.start>=end)continue;const s=Math.max(start,interval.start),e=Math.min(end,interval.end);if(s>cursor)slots.push({start:cursor,end:s});cursor=Math.max(cursor,e);}if(cursor<end)slots.push({start:cursor,end});return slots;}
function eventTime(part){return String(part?.dateTime||"").slice(11,16);}
function renderMetrics(){const totalOpen=freeSlots(false).reduce((s,x)=>s+x.end-x.start,0),planned=plans().reduce((s,p)=>s+duration(p.start,p.end),0),remaining=freeSlots(true).reduce((s,x)=>s+x.end-x.start,0),burden=totalOpen?Math.min(150,Math.round(planned/(totalOpen*(1-state.settings.buffer/100))*100)):0,overdue=activeTasks().filter(t=>t.status!=="完了"&&t.dueDate&&t.dueDate<state.date).length,follow=plans().filter(p=>p.section==="育てる"&&!p.todayDone).length;$("metrics").innerHTML=`<div><span>▤ 今日の負荷</span><strong class="${burden>100?"danger-text":""}">${burden}%</strong><i><b style="width:${Math.min(100,burden)}%"></b></i></div><div><span>◷ 空き時間</span><strong>${formatLongMinutes(remaining)}</strong><i><b style="width:${totalOpen?remaining/totalOpen*100:0}%"></b></i></div><div><span>⚠ 期限超過</span><strong class="danger-text">${overdue}件</strong></div><div><span>♟ 部下フォロー</span><strong>${follow}件</strong></div>`;}
function renderTimeline(){const start=timeToMin(state.settings.dayStart),end=timeToMin(state.settings.dayEnd),range=Math.max(60,end-start),items=[];state.events.filter(e=>!e.isAllDay).forEach(e=>items.push({type:"event",id:e.id,start:eventTime(e.start),end:eventTime(e.end),title:e.subject||"予定",subtitle:e.location?.displayName||"Outlook予定",source:"NOLTY",webLink:e.webLink||""}));plans().forEach(p=>items.push({type:"task",id:p.id,start:p.start,end:p.end,title:p.title,subtitle:p.subtitle,source:"TASK",todayDone:p.todayDone}));items.sort((a,b)=>timeToMin(a.start)-timeToMin(b.start));let html=`<div class="time-scale">`;for(let m=Math.ceil(start/60)*60;m<=end;m+=60)html+=`<span style="top:${(m-start)/range*100}%">${minToTime(m)}</span>`;html+=`</div><div class="time-track">`;
  for(const item of items){const s=Math.max(start,timeToMin(item.start)),e=Math.min(end,timeToMin(item.end));if(e<=s)continue;const top=(s-start)/range*100,height=Math.max(4,(e-s)/range*100),cls=item.type==="event"?"event-block":"task-block";html+=`<button class="timeline-block ${cls} ${item.todayDone?"done":""}" data-${item.type}="${esc(item.id)}" style="top:${top}%;height:${height}%"><span>${esc(item.start)} - ${esc(item.end)}</span><strong>${esc(item.title)}</strong><small>${esc(item.subtitle)}</small><em>${item.source}</em></button>`;}
  for(const slot of freeSlots(true)){if(slot.end-slot.start<15)continue;const top=(slot.start-start)/range*100,height=(slot.end-slot.start)/range*100;html+=`<div class="empty-block" style="top:${top}%;height:${height}%"><span>${minToTime(slot.start)} - ${minToTime(slot.end)}</span>（空き時間）</div>`;}
  $("timeline").innerHTML=html+`</div>`;
}
function renderSections(){const groups=Object.fromEntries(SECTIONS.map(x=>[x,[]]));plans().forEach(p=>groups[p.section]?.push(p));const meta={"守る":["🛡","品質・安全・納期を守る"],"進める":["↗","今、前に進める"],"育てる":["♟","人と組織を育てる"]};$("sectionCards").innerHTML=SECTIONS.map(section=>`<section class="section-card section-${section}"><header><span>${meta[section][0]}</span><div><h2>${section}</h2><p>${meta[section][1]}</p></div></header><div>${groups[section].slice(0,4).map(p=>`<button data-plan="${esc(p.id)}"><i class="check ${p.todayDone?"checked":""}">${p.todayDone?"✓":""}</i><span>${esc(p.title)}</span></button>`).join("")||`<p class="empty-note">配置されたタスクはありません</p>`}</div></section>`).join("");}
function promptRecord(key){return activeTodayRecords().find(r=>r.kind==="PROMPT"&&r.sourceId===key);}
function renderPrompts(){$("promptGrid").innerHTML=PROMPTS.map(([key,title,sub])=>{const record=promptRecord(key);return`<label><strong>${esc(title)}</strong><small>${esc(sub)}</small><textarea data-prompt="${key}" rows="2" placeholder="今日の答えを入力">${esc(record?.value||"")}</textarea></label>`;}).join("");}
function renderFocus(){let focus=plans().filter(p=>p.focusRank>0).sort((a,b)=>a.focusRank-b.focusRank);if(!focus.length)focus=plans().filter(p=>!p.todayDone).slice(0,3);$("focusList").innerHTML=focus.slice(0,3).map((p,i)=>`<button data-plan="${esc(p.id)}"><b>${String(p.focusRank||i+1).padStart(2,"0")}</b><span>${esc(p.title)}</span><em>${esc(state.tasks[p.sourceId]?.owner||state.settings.owner)}</em><time>${esc(p.end||"—")}</time><i>TASK</i></button>`).join("")||`<p class="empty-note">自動作成すると重点3本が表示されます</p>`;}
function carryTasks(){const scheduled=new Set(plans().map(p=>p.sourceId));return eligibleTasks().filter(t=>!scheduled.has(t.id));}
function memoRecord(){return activeTodayRecords().find(r=>r.kind==="MEMO"&&r.sourceId==="interrupt");}
function renderFooter(){const carry=carryTasks();$("carryCount").textContent=carry.length;$("interruptMemo").value=memoRecord()?.value||"";$("carryList").innerHTML=candidateRows(carry,false);const ds=dayState();$("closeDayBtn").innerHTML=ds.closed?`✓ 今日を閉じました<small>振り返り保存済み</small>`:`☾ 今日を閉じる<small>1日の振り返りを行います</small>`;}
function candidateRows(tasks,add=true){return tasks.map(t=>`<article><div><strong>${esc(t.title)}</strong><small>${esc(t.category)}｜${esc(tempValue(t.priority))}｜期日 ${esc(t.dueDate||"未設定")}｜${t.expectedMinutes?formatHours(t.expectedMinutes/60):"時間未設定"}</small></div>${add?`<button data-add-task="${esc(t.id)}">今日へ追加</button>`:""}</article>`).join("")||`<p class="empty-note">対象はありません</p>`;}

function deletePlansForDate(){plans().forEach(p=>touchRecord(p,{deleted:true}));}
function createPlan(task,start,end,index,focusRank=0){return newRecord("TASK_PLAN",{sourceId:task.id,title:task.title,subtitle:task.nextAction||task.category,start:minToTime(start),end:minToTime(end),plannedHours:(end-start)/60,section:taskSection(task),focusRank,sortOrder:index+1});}
function buildAutomaticPlan(){if(dayState().confirmed&&!confirm("確定済みの今日を再構成しますか？\n手動で調整した配置は作り直されます。"))return;deletePlansForDate();const slots=freeSlots(false).map(x=>({...x})),open=slots.reduce((s,x)=>s+x.end-x.start,0),budget=Math.floor(open*(1-state.settings.buffer/100)/15)*15;let used=0,index=0,focusCount=0;
  for(const task of eligibleTasks()){
    let need=Math.round((Number(task.expectedMinutes)||0)/15)*15;if(!need)continue;const split=task.workSplit==="分割可",minimum=Math.max(15,Math.round((Number(task.minimumBlockMinutes)||30)/15)*15),forced=task.todayPlacement==="必ず入れる";
    if(!forced&&used>=budget)break;
    if(!split){const slot=slots.find(x=>x.end-x.start>=need&&x.end>x.start);if(!slot||(!forced&&used+need>budget))continue;createPlan(task,slot.start,slot.start+need,index++,focusCount<3?++focusCount:0);slot.start+=need;used+=need;continue;}
    let remaining=Math.min(need,forced?open-used:Math.max(0,budget-used)),first=true;for(const slot of slots){const available=slot.end-slot.start,piece=Math.floor(Math.min(available,remaining)/15)*15;if(piece<minimum)continue;createPlan(task,slot.start,slot.start+piece,index++,first&&focusCount<3?++focusCount:0);first=false;slot.start+=piece;remaining-=piece;used+=piece;if(remaining<minimum)break;}
  }
  saveDayState({confirmed:false,closed:false,rebuiltAt:nowIso()});store();render();scheduleSync(1200,"今日を自動作成");
}
function earliestSlot(minutes){return freeSlots(true).find(x=>x.end-x.start>=minutes);}
function addTaskToToday(taskId){const task=state.tasks[taskId];if(!task)return;const expected=Math.max(15,Number(task.expectedMinutes)||60),minutes=task.workSplit==="分割可"?Math.max(15,Math.min(expected,120)):expected,slot=earliestSlot(minutes);if(!slot){alert("配置できる空き時間がありません。設定の表示時間または既存配置を確認してください。");return;}const usedRanks=new Set(plans().map(p=>Number(p.focusRank)||0)),rank=[1,2,3].find(x=>!usedRanks.has(x))||0;createPlan(task,slot.start,slot.start+minutes,plans().length,rank);store();render();scheduleSync();$("candidateDialog").close();}
function openPlan(id){const plan=state.records[id],task=state.tasks[plan?.sourceId];if(!plan||!task)return;state.editingPlan=id;$("planTitle").textContent=plan.title;$("planSubtitle").textContent=`TaskID：${task.id}｜${task.category}｜担当 ${task.owner||"未設定"}`;const form=$("planForm");form.elements.start.value=plan.start;form.elements.end.value=plan.end;form.elements.section.value=plan.section;form.elements.focusRank.value=plan.focusRank||0;form.elements.todayDone.value=String(Boolean(plan.todayDone));form.elements.status.value=task.status||"未着手";form.elements.progress.value=Number(task.progress)||0;form.elements.priority.value=tempValue(task.priority);form.elements.dueDate.value=task.dueDate||"";form.elements.nextTouchDate.value=task.nextTouchDate||"";form.elements.expectedHours.value=task.expectedMinutes?task.expectedMinutes/60:"";form.elements.notes.value=plan.notes||"";$("planDialog").showModal();}
function patchTask(task,changes){const existing=state.taskPatches[task.id]||{baseRevision:Number(task.revision)||1,baseValues:{},changes:{},title:task.title};for(const key of Object.keys(changes))if(!(key in existing.baseValues))existing.baseValues[key]=task[key]??"";Object.assign(existing.changes,changes);state.taskPatches[task.id]=existing;Object.assign(task,changes,{updatedAt:nowIso(),updatedBy:deviceId(),revision:(Number(task.revision)||0)+1});store();}
function savePlan(event){event.preventDefault();const plan=state.records[state.editingPlan],task=state.tasks[plan?.sourceId],data=Object.fromEntries(new FormData(event.currentTarget).entries());if(!plan||!task)return;const start=timeToMin(data.start),end=timeToMin(data.end);if(end<=start){alert("終了時刻は開始時刻より後にしてください。");return;}const sameRank=plans().find(p=>p.id!==plan.id&&Number(p.focusRank)===Number(data.focusRank)&&Number(data.focusRank)>0);if(sameRank)touchRecord(sameRank,{focusRank:0});touchRecord(plan,{start:data.start,end:data.end,plannedHours:(end-start)/60,section:data.section,todayDone:data.todayDone==="true",focusRank:Number(data.focusRank)||0,notes:data.notes||""});const changes={status:data.status,progress:data.status==="完了"?100:Math.max(0,Math.min(100,Math.round((Number(data.progress)||0)/5)*5)),priority:data.priority,dueDate:data.dueDate,nextTouchDate:data.nextTouchDate,expectedMinutes:Math.max(0,Math.round((Number(data.expectedHours)||0)*4)*15)};patchTask(task,changes);$("planDialog").close();render();scheduleSync();}
function removePlan(){const plan=state.records[state.editingPlan];if(plan){touchRecord(plan,{deleted:true});$("planDialog").close();render();}}
function savePrompt(key,value){let record=promptRecord(key);if(!record)record=newRecord("PROMPT",{sourceId:key,title:PROMPTS.find(x=>x[0]===key)?.[1]||key});touchRecord(record,{value});}
function saveMemo(value){let record=memoRecord();if(!record)record=newRecord("MEMO",{sourceId:"interrupt",title:"割込みメモ"});touchRecord(record,{value});}

async function ensureJsZip(){if(globalThis.JSZip)return;await new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=new URL("./jszip.min.js",document.baseURI).href;script.onload=resolve;script.onerror=()=>reject(new Error("Excel同期部品の読込に失敗しました"));document.head.append(script);});}
function configReady(){return CONFIG.CLIENT_ID&&!CONFIG.CLIENT_ID.includes("YOUR_")&&CONFIG.REDIRECT_URI&&!CONFIG.REDIRECT_URI.includes("YOUR-");}
async function initializeAuth(){if(!configReady()){setSync("warn","Microsoft設定待ち");return;}state.msal=new PublicClientApplication({auth:{clientId:CONFIG.CLIENT_ID,authority:CONFIG.AUTHORITY,redirectUri:CONFIG.REDIRECT_URI,navigateToLoginRequestUrl:false},cache:{cacheLocation:"localStorage",storeAuthStateInCookie:true}});await state.msal.initialize();const response=await state.msal.handleRedirectPromise();state.account=response?.account||state.msal.getAllAccounts()[0]||null;if(state.account){state.msal.setActiveAccount(state.account);localStorage.setItem(LOGIN_KEY,state.account.username||"");await sync({automatic:true});}updateAccount();}
async function login(){if(!state.msal)return alert("先にapp-config.jsへClient IDと公開URLを設定してください。");await state.msal.loginRedirect({scopes:CONFIG.GRAPH_SCOPES,prompt:"select_account",redirectUri:CONFIG.REDIRECT_URI});}
async function token(){if(!state.account)throw new Error("Microsoftログインが必要です");try{return(await state.msal.acquireTokenSilent({scopes:CONFIG.GRAPH_SCOPES,account:state.account})).accessToken;}catch(e){if(e instanceof InteractionRequiredAuthError||/interaction_required|consent_required|login_required/i.test(e.errorCode||"")){await state.msal.acquireTokenRedirect({scopes:CONFIG.GRAPH_SCOPES,account:state.account,redirectUri:CONFIG.REDIRECT_URI,loginHint:state.account.username||localStorage.getItem(LOGIN_KEY)||undefined});return null;}throw e;}}
function graphError(response,payload={}){const e=new Error(payload?.error?.message||`HTTP ${response.status}`);e.errorCode=`GRAPH_${response.status}_${payload?.error?.code||"HTTP"}`;e.httpStatus=response.status;return e;}
const fileMetaUrl=name=>`https://graph.microsoft.com/v1.0/me/drive/special/approot:/${encodeURIComponent(name)}?$select=id,name,eTag,lastModifiedDateTime,webUrl,size`;
async function fetchFile(tok,name,parser){await fetch("https://graph.microsoft.com/v1.0/me/drive/special/approot?$select=id",{headers:{Authorization:`Bearer ${tok}`}});const mr=await fetch(fileMetaUrl(name),{headers:{Authorization:`Bearer ${tok}`}});if(mr.status===404)return{exists:false,records:{},bytes:null,id:"",eTag:"",webUrl:""};if(!mr.ok){let p={};try{p=await mr.json();}catch{}throw graphError(mr,p);}const meta=await mr.json(),cr=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(meta.id)}/content`,{headers:{Authorization:`Bearer ${tok}`}});if(!cr.ok)throw graphError(cr);const bytes=await cr.arrayBuffer(),list=await parser(bytes),records={};list.forEach(r=>records[r.id]=r);return{exists:true,records,bytes,id:meta.id,eTag:meta.eTag,webUrl:meta.webUrl||""};}
async function uploadFile(tok,name,bytes,remote,mime){const headers={Authorization:`Bearer ${tok}`,"Content-Type":mime,Accept:"application/json"};if(remote?.eTag)headers["If-Match"]=remote.eTag;const url=remote?.id?`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(remote.id)}/content`:`https://graph.microsoft.com/v1.0/me/drive/special/approot:/${encodeURIComponent(name)}:/content`,response=await fetch(url,{method:"PUT",headers,body:bytes});if(!response.ok){let p={};try{p=await response.json();}catch{}throw graphError(response,p);}return response.json();}
function recordSignature(r){return JSON.stringify([r.id,r.date,r.kind,r.sourceId,r.title,r.subtitle,r.start,r.end,r.plannedHours,r.section,r.todayDone,r.focusRank,r.sortOrder,r.notes,r.value,r.updatedAt,r.updatedBy,r.revision,r.deleted]);}
function mergeToday(remote,manual){const merged={},conflicts=[],ids=new Set([...Object.keys(state.records),...Object.keys(remote)]);for(const id of ids){const l=state.records[id],r=remote[id],b=state.base[id];if(!l){merged[id]=r;continue;}if(!r){merged[id]=l;continue;}if(recordSignature(l)===recordSignature(r)){merged[id]=Date.parse(l.updatedAt)>=Date.parse(r.updatedAt)?l:r;continue;}const lc=!b||recordSignature(l)!==recordSignature(b),rc=!b||recordSignature(r)!==recordSignature(b);if(lc&&rc){conflicts.push(id);merged[id]=manual&&confirm(`TODAYの「${l.title||r.title}」が別端末でも変更されています。\n\nOK：この端末を優先\nキャンセル：OneDriveを優先`)?l:r;}else merged[id]=lc?l:rc?r:Date.parse(l.updatedAt)>=Date.parse(r.updatedAt)?l:r;}return{merged,conflicts};}
async function applyTaskPatches(tok,remote,automatic){const patches=Object.entries(state.taskPatches);if(!patches.length)return remote;const records={...remote.records};for(const [taskId,patch] of patches){const task=records[taskId];if(!task)continue;const conflict=Object.keys(patch.changes).some(key=>String(task[key]??"")!==String(patch.baseValues[key]??""));if(conflict&&automatic)throw Object.assign(new Error(`TASK CONTROLとの同期競合：${patch.title}`),{errorCode:"TASK_CONFLICT"});if(conflict&&!confirm(`「${patch.title}」はTASK CONTROL側でも変更されています。\n\nOK：TODAYの変更を優先\nキャンセル：TASK CONTROLを優先`))continue;Object.assign(task,patch.changes,{updatedAt:nowIso(),updatedBy:deviceId(),revision:(Number(task.revision)||0)+1});}
  const bytes=await buildTaskWorkbook(Object.values(records),remote.bytes),uploaded=await uploadFile(tok,CONFIG.TASK_FILE_NAME,bytes,remote,TASK_MIME);state.taskPatches={};return{...remote,records,bytes,id:uploaded.id||remote.id,eTag:uploaded.eTag||remote.eTag,webUrl:uploaded.webUrl||remote.webUrl};}
async function fetchEvents(tok){const start=`${state.date}T00:00:00+09:00`,end=`${addDays(state.date,1)}T00:00:00+09:00`,url=`https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=${encodeURIComponent(start)}&endDateTime=${encodeURIComponent(end)}&$select=id,subject,start,end,location,isAllDay,isCancelled,webLink&$orderby=start/dateTime`;
  const response=await fetch(url,{headers:{Authorization:`Bearer ${tok}`,Accept:"application/json",Prefer:'outlook.timezone="Tokyo Standard Time"'}});if(!response.ok){let p={};try{p=await response.json();}catch{}throw graphError(response,p);}state.events=(await response.json()).value?.filter(e=>!e.isCancelled)||[];}
async function sync({automatic=false}={}){if(!state.account||state.busy)return false;clearTimeout(state.syncTimer);state.busy=true;$("syncBtn").disabled=true;setSync("working","同期中…");try{await ensureJsZip();const tok=await token();if(!tok)return false;let taskRemote=await fetchFile(tok,CONFIG.TASK_FILE_NAME,parseTaskWorkbook);if(!taskRemote.exists)throw new Error("TASK_CONTROL_Master.xlsxが見つかりません。同じClient IDとOneDrive AppFolderを使用してください。");taskRemote=await applyTaskPatches(tok,taskRemote,automatic);state.taskRemote=taskRemote;state.tasks=taskRemote.records;
    const todayRemote=await fetchFile(tok,CONFIG.TODAY_FILE_NAME,parseTodayWorkbook),result=mergeToday(todayRemote.records,!automatic);if(result.conflicts.length&&automatic)throw Object.assign(new Error(`TODAY同期競合 ${result.conflicts.length}件`),{errorCode:"TODAY_CONFLICT"});const template=todayRemote.bytes||await(await fetch(new URL("./BUCHO_TODAY_Master.xlsx",document.baseURI))).arrayBuffer(),bytes=await buildTodayWorkbook(Object.values(result.merged),template),uploaded=await uploadFile(tok,CONFIG.TODAY_FILE_NAME,bytes,todayRemote,TODAY_MIME);state.records=result.merged;state.base=structuredClone(result.merged);state.todayRemote={...todayRemote,id:uploaded.id||todayRemote.id,eTag:uploaded.eTag||todayRemote.eTag,webUrl:uploaded.webUrl||todayRemote.webUrl};await fetchEvents(tok);store();setSync("synced",`同期成功｜${tokyoTime()}`);state.lastError=null;render();return true;
  }catch(e){state.lastError={code:e.errorCode||e.name,message:String(e.message||e)};setSync("error",`同期失敗｜${state.lastError.code}`);if(!automatic)alert(`${state.lastError.message}\n\nExcel Masterを閉じ、同じMicrosoftアカウントで再度お試しください。`);return false;}finally{state.busy=false;$("syncBtn").disabled=false;}}
function scheduleSync(delay=CONFIG.AUTO_SYNC_DELAY_MS||6000,message=""){clearTimeout(state.syncTimer);setSync("local",state.account?`${message||"変更を端末内保存"}｜自動同期待ち`:message||"端末内保存");if(state.account)state.syncTimer=setTimeout(()=>sync({automatic:true}),delay);}
function setSync(cls,text){const indicator=$("syncState"),button=$("syncBtn");if(indicator){indicator.className=`sync-indicator ${cls}`;indicator.textContent=text;}if(button){button.textContent=cls==="working"?"↻ 同期中…":"↻ 同期";button.setAttribute("aria-busy",String(cls==="working"));}}
function updateAccount(){$("loginBtn").textContent=state.account?"アカウント切替":"Microsoftログイン";$("accountInfo").textContent=state.account?(state.account.username||state.account.name||"Microsoft接続済"):"Microsoft未接続";$("taskExcelBtn").disabled=!state.taskRemote?.id;$("todayExcelBtn").disabled=!state.todayRemote?.id;}
async function openExcel(which){const remote=which==="task"?state.taskRemote:state.todayRemote;if(!remote?.id)return;const popup=window.open("about:blank","_blank");try{const tok=await token(),response=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(remote.id)}/preview`,{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:"{}"}),payload=await response.json();if(!response.ok)throw graphError(response,payload);popup.location.replace(payload.getUrl);}catch(e){popup?.close();alert(e.message);}}

function changeDate(delta){state.date=addDays(state.date,delta);state.events=[];render();if(state.account)token().then(t=>t&&fetchEvents(t).then(render)).catch(()=>{});}
function openCandidates(){$("candidateList").innerHTML=candidateRows(carryTasks(),true);$("candidateDialog").showModal();}
function saveSettings(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());state.settings={owner:String(data.owner||"福本").trim(),buffer:Math.max(0,Math.min(70,Number(data.buffer)||0)),dayStart:data.dayStart,dayEnd:data.dayEnd,lunchStart:data.lunchStart,lunchEnd:data.lunchEnd};if(timeToMin(state.settings.dayEnd)<=timeToMin(state.settings.dayStart)){alert("表示終了は表示開始より後にしてください。");return;}store();$("settingsDialog").close();render();}
function openSettings(){const f=$("settingsForm");Object.entries(state.settings).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v;});$("settingsDialog").showModal();}
function diagnostics(){return JSON.stringify({appVersion:CONFIG.APP_VERSION,checkedAtTokyo:new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",dateStyle:"medium",timeStyle:"medium"}).format(new Date()),date:state.date,configuredRedirectUri:CONFIG.REDIRECT_URI,clientId:CONFIG.CLIENT_ID,signedIn:Boolean(state.account),account:state.account?.username||null,taskCount:activeTasks().length,todayPlanCount:plans().length,eventCount:state.events.length,pendingTaskPatchCount:Object.keys(state.taskPatches).length,todayRecordCount:Object.keys(state.records).length,settings:state.settings,lastError:state.lastError},null,2);}

$("prevDay").onclick=()=>changeDate(-1);$("nextDay").onclick=()=>changeDate(1);$("calendarBtn").onclick=()=>{state.date=tokyoDate();changeDate(0);};$("rebuildBtn").onclick=buildAutomaticPlan;$("confirmBtn").onclick=()=>{saveDayState({confirmed:!dayState().confirmed});render();};$("syncBtn").onclick=()=>state.account?sync():login();$("loginBtn").onclick=login;$("settingsBtn").onclick=openSettings;$("allTasksBtn").onclick=openCandidates;$("carryBtn").onclick=()=>$("carryDialog").showModal();$("planForm").onsubmit=savePlan;$("removePlanBtn").onclick=removePlan;$("settingsForm").onsubmit=saveSettings;
$("closeDayBtn").onclick=()=>{const current=dayState().closed;if(!current){const reflection=prompt("今日の振り返りを一言で残しますか？",dayState().reflection||"");if(reflection===null)return;saveDayState({closed:true,confirmed:true,reflection,closedAt:nowIso()});}else if(confirm("今日を再び開きますか？"))saveDayState({closed:false});render();};
$("interruptMemo").onchange=e=>saveMemo(e.target.value);$("promptGrid").onchange=e=>{if(e.target.dataset.prompt)savePrompt(e.target.dataset.prompt,e.target.value);};
$("timeline").onclick=e=>{const task=e.target.closest("[data-task]"),event=e.target.closest("[data-event]");if(task)openPlan(task.dataset.task);else if(event){const item=state.events.find(x=>x.id===event.dataset.event);if(item?.webLink)window.open(item.webLink,"_blank","noopener");}};
$("sectionCards").onclick=e=>{const target=e.target.closest("[data-plan]");if(target)openPlan(target.dataset.plan);};$("focusList").onclick=e=>{const target=e.target.closest("[data-plan]");if(target)openPlan(target.dataset.plan);};$("candidateList").onclick=e=>{const target=e.target.closest("[data-add-task]");if(target)addTaskToToday(target.dataset.addTask);};
$("todayExcelBtn").onclick=()=>openExcel("today");$("taskExcelBtn").onclick=()=>openExcel("task");$("diagnosticBtn").onclick=()=>{$("diagnosticText").textContent=diagnostics();$("diagnosticDialog").showModal();};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());
window.addEventListener("online",()=>state.account&&sync({automatic:true}));document.addEventListener("visibilitychange",()=>document.visibilityState==="visible"&&state.account&&sync({automatic:true}));setInterval(()=>state.account&&sync({automatic:true}),Math.max(1,CONFIG.AUTO_PULL_MINUTES||3)*60000);
render();initializeAuth().catch(e=>{state.lastError={code:e.errorCode||e.name,message:String(e.message||e)};setSync("error",`認証初期化失敗｜${state.lastError.code}`);});
